library:
  source-dirs: src
tests:
  secret-sharing-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secret-sharing
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- formatting
- clock
- base >= 4.7 && < 5
- reflection
- cryptonite
- vector
- modular-arithmetic
name: secret-sharing
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/secret-sharing
license: BSD3
executables:
  secret-sharing-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - secret-sharing
description: Please see the README on GitHub at <https://github.com/githubuser/secret-sharing#readme>
